# docker/docker-compose.yml
services:
  eudic-maimemo-sync:
    image: ghcr.io/emuqi/eudic-maimemo-sync:latest
    container_name: eudic-maimemo-sync
    restart: unless-stopped
    env_file:
      - .env
    # volumes:
    #   - ./words_data.txt:/app/words_data.txt # Keep if needed
    environment:
      - TZ=Asia/Shanghai
      - RUN_ON_STARTUP=true # Add this to run the sync when the container starts
      # Example: Run every hour at minute 0
      - CRON_SCHEDULE=0 * * * *
      # Example: Run daily at 3:15 AM
      # - CRON_SCHEDULE=15 3 * * *
      # Ensure all necessary variables (EUDIC_API_KEY etc.) are in .env or here
    healthcheck:
      # Test if the supercronic process is running
      test: ["CMD-SHELL", "pgrep supercronic || exit 1"]
      interval: 2m
      timeout: 5s
      retries: 3
      start_period: 10s # Give supercronic time to start